for i in range(51): print(i, end=" ")
print()
for i in range(50, -1, -1): print(i, end=" ")
print()
for i in range(30, 51): print(i, end=" ")
print()
for i in range(50, 9, -2): print(i, end=" ")
print()
for i in range(100, 201, 5): print(i, end=" ")
print()